### ISSUE TITLE
Tests failing on Fedora 28+

### ISSUE THREAD

**Issue by QuLogic** [jupyter/jupyter_kernel_test#42]
On Fedora 28 (and Rawhide), the `test_is_complete` test is now failing:
```
======================================================================
FAIL: test_is_complete (__main__.IPyKernelTests) (status='complete')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/jupyter_kernel_test-0.3/jupyter_kernel_test/__init__.py", line 160, in test_is_complete
    self.check_is_complete(sample, 'complete')
  File "/builddir/build/BUILD/jupyter_kernel_test-0.3/jupyter_kernel_test/__init__.py", line 148, in check_is_complete
    reply['content']['status']))
AssertionError: For code sample
  'def f(x):\n  return x*2\n\n'
Expected 'complete', got 'incomplete'.
```
It continues to work fine on Fedora 27. Unfortunately, I did not check into this for a while so many things have changed since it started failing. I will try to figure out exactly what the difference between the two is, but if you have any ideas where to look, that would be helpful.

**Comment by hroncok** [comment]
I cane reproduce this with Python 3.5 to 3.7.

```console
$ pip freeze
backcall==0.1.0
decorator==4.3.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.1
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
parso==0.3.0
pexpect==4.6.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.6.0
Pygments==2.2.0
python-dateutil==2.7.3
pyzmq==17.0.0
simplegeneric==0.8.1
six==1.11.0
tornado==5.0.2
traitlets==4.3.2
wcwidth==0.1.7
```

**Comment by takluyver** [comment]
I think the behaviour of IPython changed. Running the tests against the IPython kernel is a somewhat lazy but convenient way of testing this module. I think sticking another newline on the end of the sample should fix it.

**Comment by hroncok** [comment]
Thank you. Confirmed.
