### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kylebarron** [jupyter/jupyter_kernel_test#48]
Hello,

There have been 24 commits since the current PyPI version was released a year and a half ago. I tried installing from master but wasn't able to (traceback below). Is there likely to be a new release soon or should I stick with the published 0.3 version?

```
> pip install git+https://github.com/jupyter/jupyter_kernel_test --upgrade
Collecting git+https://github.com/jupyter/jupyter_kernel_test
  Cloning https://github.com/jupyter/jupyter_kernel_test to /private/var/folders/7d/70k76kz578nd6m192964n7300000gn/T/pip-req-build-jv87hd0f
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/kylebarron/anaconda/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/7d/70k76kz578nd6m192964n7300000gn/T/pip-req-build-jv87hd0f/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7d/70k76kz578nd6m192964n7300000gn/T/pip-req-build-jv87hd0f/
```

**Comment by blink1073** [comment]
Done!
