### ISSUE TITLE
tests broken as of master

### ISSUE THREAD

**Issue by anntzer** [jupyter/jupyter_kernel_test#51]
From git HEAD, in an environment with up to date jupyter (`pip list -o` shows nothing jupyter-related), `pytest test_ipykernel.py` results in (in particular)
```
_________________________________________________________________________________ IPyKernelTests.test_display_data _________________________________________________________________________________

self = <test_ipykernel.IPyKernelTests testMethod=test_display_data>

    def test_display_data(self):
        if not self.code_display_data:
            raise SkipTest
    
        for sample in self.code_display_data:
            with self.subTest(code=sample['code']):
                reply, output_msgs = self.execute_helper(sample['code'])
    
                self.assertEqual(reply.content['status'], 'ok')
    
                self.assertGreaterEqual(len(output_msgs), 1)
>               self.assertEqual(output_msgs[0].header['msg_type'], 'display_data')
E               AssertionError: 'error' != 'display_data'
E               - error
E               + display_data

jupyter_kernel_test/__init__.py:244: AssertionError
---------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------
ERROR    traitlets:client.py:118 Exception from message handler <function IOLoopKernelClient._execution_future.<locals>.watch_for_idle at 0x7fe971d89d90>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jupyter_kernel_mgmt/client.py", line 115, in _call_handlers
    handler(msg, channel)
TypeError: watch_for_idle() takes 1 positional argument but 2 were given
ERROR    traitlets:client.py:118 Exception from message handler <function IOLoopKernelClient._execution_future.<locals>.watch_for_idle at 0x7fe971d89d90>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jupyter_kernel_mgmt/client.py", line 115, in _call_handlers
    handler(msg, channel)
TypeError: watch_for_idle() takes 1 positional argument but 2 were given
ERROR    traitlets:client.py:118 Exception from message handler <function IOLoopKernelClient._execution_future.<locals>.watch_for_idle at 0x7fe971d89d90>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jupyter_kernel_mgmt/client.py", line 115, in _call_handlers
    handler(msg, channel)
TypeError: watch_for_idle() takes 1 positional argument but 2 were given
ERROR    traitlets:client.py:118 Exception from message handler <function IOLoopKernelClient._execution_future.<locals>.watch_for_idle at 0x7fe971d89d90>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jupyter_kernel_mgmt/client.py", line 115, in _call_handlers
    handler(msg, channel)
TypeError: watch_for_idle() takes 1 positional argument but 2 were given
```

**Comment by blink1073** [comment]
Fixed in #57
