### ISSUE TITLE
installation in conda

### ISSUE THREAD

**Issue by videlec** [jupyter/jupyter_kernel_test#70]
I created a conda environment with `python-3.9` and `jupyter_kernel_test` (that is thankfully available on conda-forge). However, running the sample test file I got an `ImportError` raised in `jupyter_kernel_tests/__init__.py` file
```
$ python test_gpkernel.py 
Traceback (most recent call last):
  File "pari-jupyter/test/test_gpkernel.py", line 7, in <module>
    import jupyter_kernel_test as jkt
  File ".../lib/python3.9/site-packages/jupyter_kernel_test/__init__.py", line 11, in <module>
    from jupyter_client.utils import run_sync
ImportError: cannot import name 'run_sync' from 'jupyter_client.utils' (.../lib/python3.9/site-packages/jupyter_client/utils.py)
```

**Comment by videlec** [comment]
The function is only available in more recent `pari_jupyter_kernel` that includes jupyter/jupyter_client#623

**Comment by videlec** [comment]
(but conda only ships jupyter_client 6.1.2 from march 2021)
